export interface MYGAProduct {
  id: number;
  carrier: string;
  product: string;
  amBest: string;
  term: number;
  rate: number;
  minPremium: number;
  maxPremium: number | null;
  bonus: number;
  mva: boolean;
  surrenderSchedule: number[];
  renewalType: "Declared Rate" | "Indexed Option" | "Par Rate";
  premiumBands: { min: number; max: number | null; rate: number }[];
  states: "All" | string[];
  notes: string;
}

export const MYGA_PRODUCTS: MYGAProduct[] = [
  {
    id: 1,
    carrier: "American National",
    product: "Palladium MYG 5",
    amBest: "A",
    term: 5,
    rate: 5.30,
    minPremium: 10_000,
    maxPremium: 1_000_000,
    bonus: 0,
    mva: false,
    surrenderSchedule: [8, 7, 6, 5, 4],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 10_000, max: 99_999, rate: 5.30 },
      { min: 100_000, max: null,  rate: 5.40 },
    ],
    states: "All",
    notes: "No MVA. Free withdrawal up to 10%/yr after year 1.",
  },
  {
    id: 2,
    carrier: "Athene",
    product: "MaxRate 7",
    amBest: "A",
    term: 7,
    rate: 5.55,
    minPremium: 10_000,
    maxPremium: 2_000_000,
    bonus: 0,
    mva: true,
    surrenderSchedule: [9, 8, 7, 6, 5, 4, 3],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 10_000, max: 99_999,  rate: 5.55 },
      { min: 100_000, max: 249_999, rate: 5.65 },
      { min: 250_000, max: null,    rate: 5.75 },
    ],
    states: "All",
    notes: "MVA applies during surrender period. RMD-friendly withdrawals available.",
  },
  {
    id: 3,
    carrier: "Global Atlantic",
    product: "SecureGain 3",
    amBest: "A",
    term: 3,
    rate: 5.05,
    minPremium: 10_000,
    maxPremium: 1_000_000,
    bonus: 0,
    mva: false,
    surrenderSchedule: [7, 6, 5],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 10_000, max: 99_999, rate: 5.05 },
      { min: 100_000, max: null,  rate: 5.15 },
    ],
    states: "All",
    notes: "Short-term option. Competitive 3-yr rate with no MVA.",
  },
  {
    id: 4,
    carrier: "Midland National",
    product: "Oak ADVantage 5",
    amBest: "A+",
    term: 5,
    rate: 5.45,
    minPremium: 5_000,
    maxPremium: 1_500_000,
    bonus: 0.50,
    mva: false,
    surrenderSchedule: [8, 7, 6, 5, 4],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 5_000,   max: 99_999, rate: 5.45 },
      { min: 100_000, max: null,   rate: 5.55 },
    ],
    states: "All",
    notes: "0.50% first-year premium bonus. A+ rated carrier.",
  },
  {
    id: 5,
    carrier: "North American",
    product: "Guarantee Choice 10",
    amBest: "A+",
    term: 10,
    rate: 5.60,
    minPremium: 10_000,
    maxPremium: null,
    bonus: 0,
    mva: true,
    surrenderSchedule: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 10_000,  max: 99_999,  rate: 5.60 },
      { min: 100_000, max: 499_999, rate: 5.70 },
      { min: 500_000, max: null,    rate: 5.80 },
    ],
    states: "All",
    notes: "Highest long-term rate. MVA applies. Ideal for laddering strategy.",
  },
  {
    id: 6,
    carrier: "Protective",
    product: "ProSave Elite 5",
    amBest: "A+",
    term: 5,
    rate: 5.35,
    minPremium: 10_000,
    maxPremium: 1_000_000,
    bonus: 0,
    mva: false,
    surrenderSchedule: [7, 6, 5, 4, 3],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 10_000, max: 99_999, rate: 5.35 },
      { min: 100_000, max: null,  rate: 5.45 },
    ],
    states: "All",
    notes: "A+ carrier, no MVA. Strong renewal history.",
  },
  {
    id: 7,
    carrier: "Sentinel Security Life",
    product: "Sentinel MYGA 3",
    amBest: "B++",
    term: 3,
    rate: 5.20,
    minPremium: 5_000,
    maxPremium: 500_000,
    bonus: 0,
    mva: false,
    surrenderSchedule: [7, 6, 5],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 5_000,  max: 99_999, rate: 5.20 },
      { min: 100_000, max: null,  rate: 5.25 },
    ],
    states: "All",
    notes: "Competitive rate but B++ rating — suitable for smaller allocations.",
  },
  {
    id: 8,
    carrier: "Oceanview Life",
    product: "Harbourview 5",
    amBest: "A-",
    term: 5,
    rate: 5.50,
    minPremium: 10_000,
    maxPremium: 1_000_000,
    bonus: 1.00,
    mva: false,
    surrenderSchedule: [8, 7, 6, 5, 3],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 10_000, max: 99_999, rate: 5.50 },
      { min: 100_000, max: null,  rate: 5.60 },
    ],
    states: "All",
    notes: "1% first-year bonus. No MVA. Strong gross rate for 5-yr.",
  },
  {
    id: 9,
    carrier: "American National",
    product: "Palladium MYG 7",
    amBest: "A",
    term: 7,
    rate: 5.45,
    minPremium: 10_000,
    maxPremium: 1_000_000,
    bonus: 0,
    mva: false,
    surrenderSchedule: [9, 8, 7, 6, 5, 4, 3],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 10_000, max: 99_999, rate: 5.45 },
      { min: 100_000, max: null,  rate: 5.55 },
    ],
    states: "All",
    notes: "No MVA, 7-yr. Good fit for clients with longer time horizon.",
  },
  {
    id: 10,
    carrier: "F&G Life",
    product: "F&G RetireMax 5",
    amBest: "A-",
    term: 5,
    rate: 5.40,
    minPremium: 10_000,
    maxPremium: 2_000_000,
    bonus: 0,
    mva: true,
    surrenderSchedule: [8, 7, 6, 5, 4],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 10_000,  max: 99_999,  rate: 5.40 },
      { min: 100_000, max: 249_999, rate: 5.50 },
      { min: 250_000, max: null,    rate: 5.60 },
    ],
    states: "All",
    notes: "MVA applies. High premium band rate for $250K+ clients.",
  },
  {
    id: 11,
    carrier: "Pacific Life",
    product: "Pacific MYGA 3",
    amBest: "A+",
    term: 3,
    rate: 4.95,
    minPremium: 10_000,
    maxPremium: 1_000_000,
    bonus: 0,
    mva: false,
    surrenderSchedule: [6, 5, 4],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 10_000, max: 99_999, rate: 4.95 },
      { min: 100_000, max: null,  rate: 5.05 },
    ],
    states: "All",
    notes: "A+ rated. Conservative but reliable for short-term needs.",
  },
  {
    id: 12,
    carrier: "Guggenheim Life",
    product: "Preserve MYGA 5",
    amBest: "A-",
    term: 5,
    rate: 5.60,
    minPremium: 25_000,
    maxPremium: null,
    bonus: 0,
    mva: true,
    surrenderSchedule: [9, 8, 7, 6, 5],
    renewalType: "Declared Rate",
    premiumBands: [
      { min: 25_000,  max: 99_999,  rate: 5.60 },
      { min: 100_000, max: 499_999, rate: 5.70 },
      { min: 500_000, max: null,    rate: 5.80 },
    ],
    states: "All",
    notes: "Higher minimum but among the best gross rates for 5-yr with MVA.",
  },
];

export const AM_BEST_RATINGS = ["A++", "A+", "A", "A-", "B++", "B+"];
export const MYGA_TERMS = [2, 3, 4, 5, 6, 7, 10];
