export const C = {
  bg:         "#F8FAFC",
  surface:    "#FFFFFF",
  surfaceHi:  "#F1F5F9",
  surfaceMid: "#EEF2F7",
  navy:       "#0B1C2E",
  blue:       "#2E86FF",
  blueDim:    "#EBF3FF",
  blueMid:    "#BFDBFE",
  teal:       "#19C6B4",
  tealDim:    "#E6FAF8",
  text:       "#0B1C2E",
  textMid:    "#475569",
  textDim:    "#94A3B8",
  border:     "#E2E8F0",
  borderHi:   "#CBD5E1",
  green:      "#059669",
  greenDim:   "#ECFDF5",
  red:        "#DC2626",
  redDim:     "#FEF2F2",
  amber:      "#D97706",
  amberDim:   "#FFFBEB",
  purple:     "#7C3AED",
  purpleDim:  "#F5F3FF",
};
