export const C = {
  // Brand
  navy:       "#0A2342",
  teal:       "#0D7377",
  tealLight:  "#19C6B4",
  tealDim:    "#E6FAF8",
  gold:       "#C9982A",
  goldDim:    "#FEF9EC",
  blue:       "#2E86FF",
  blueDim:    "#EBF3FF",
  blueMid:    "#BFDBFE",
  purple:     "#7C3AED",
  purpleDim:  "#F5F3FF",
  // Surfaces
  bg:         "#F4F6F9",
  surface:    "#FFFFFF",
  surfaceHi:  "#F1F5F9",
  surfaceMid: "#EEF2F7",
  // Text
  text:       "#1A1A2E",
  textMid:    "#64748B",
  textDim:    "#94A3B8",
  // Borders
  border:     "#E2E8F0",
  borderHi:   "#CBD5E1",
  // Status
  green:      "#059669",
  greenDim:   "#ECFDF5",
  red:        "#DC2626",
  redDim:     "#FEF2F2",
  amber:      "#D97706",
  amberDim:   "#FFFBEB",
};
